export const config = {
    coupleNames: process.env.NEXT_PUBLIC_COUPLE_NAMES || "Abuki & Asla",
    eventDate: process.env.NEXT_PUBLIC_EVENT_DATE || "2026-04-04T18:00:00",
    birthdayGirl: process.env.NEXT_PUBLIC_BRIDE_NAME || "Asla",
    birthdayGirlFull: process.env.NEXT_PUBLIC_BRIDE_FULL_NAME || "Asla",
    groom: process.env.NEXT_PUBLIC_GROOM_NAME || "Abuki",
    groomNickName: process.env.NEXT_PUBLIC_GROOM_NICKNAME || "Abuki",
    groomInstagram: process.env.NEXT_PUBLIC_GROOM_INSTAGRAM || "abuki",
    groomBio: process.env.NEXT_PUBLIC_GROOM_BIO || "The one who makes every moment count — full of energy, laughter, and a love so genuine it lights up every room he walks into.",
    bride: process.env.NEXT_PUBLIC_BRIDE_NAME || "Asla",
    brideNickName: process.env.NEXT_PUBLIC_BRIDE_NICKNAME || "Asla",
    brideInstagram: process.env.NEXT_PUBLIC_BRIDE_INSTAGRAM || "asla",
    brideBio: process.env.NEXT_PUBLIC_BRIDE_BIO || "A radiant soul whose smile can brighten the darkest day — kind, strong, beautiful inside and out. Today, we celebrate her.",
    bibleVerse: process.env.NEXT_PUBLIC_BIBLE_VERSE || "Happy Birthday, Asla",
    bibleVerseContent: process.env.NEXT_PUBLIC_BIBLE_VERSE_CONTENT || "May this new chapter of your life be filled with joy, love, and all the beautiful things you deserve. Here's to you — the one who makes every day brighter.",
    timeline_1: process.env.NEXT_PUBLIC_YEAR_1 || "When It All Began",
    timeline_1_content: process.env.NEXT_PUBLIC_YEAR_1_CONTENT || "From the very first moment, there was something special — a spark that turned into laughter, into trust, into something neither of us could explain but both of us felt.",
    timeline_2: process.env.NEXT_PUBLIC_YEAR_2 || "Every Moment Together",
    timeline_2_content: process.env.NEXT_PUBLIC_YEAR_2_CONTENT || "Through every adventure, every quiet evening, every shared smile — our story grew deeper, richer, and more beautiful with every passing day.",
    timeline_3: process.env.NEXT_PUBLIC_YEAR_3 || "Today & Always",
    timeline_3_content: process.env.NEXT_PUBLIC_YEAR_3_CONTENT || "On this special day, we celebrate not just a birthday — but a life that has brought so much love and light into our world. Here's to many more.",
    holyMatrimony: {
        enabled: process.env.NEXT_PUBLIC_HOLY_MATRIMONY === 'true',
        time: process.env.NEXT_PUBLIC_HOLY_MATRIMONY_TIME || "6:00 PM",
        place: process.env.NEXT_PUBLIC_HOLY_MATRIMONY_PLACE || "Birthday Dinner",
        place_details: process.env.NEXT_PUBLIC_HOLY_MATRIMONY_PLACE_DETAILS || "Addis Ababa, Ethiopia",
        googleMapsLink: process.env.NEXT_PUBLIC_HOLY_MATRIMONY_GOOGLE_MAPS || "#",
    },
    weddingReception: {
        enabled: process.env.NEXT_PUBLIC_WEDDING_RECEPTION === 'true',
        time: process.env.NEXT_PUBLIC_WEDDING_RECEPTION_TIME || "8:00 PM",
        place: process.env.NEXT_PUBLIC_WEDDING_RECEPTION_PLACE || "Birthday Celebration",
        place_details: process.env.NEXT_PUBLIC_WEDDING_RECEPTION_PLACE_DETAILS || "Addis Ababa, Ethiopia",
        googleMapsLink: process.env.NEXT_PUBLIC_WEDDING_RECEPTION_GOOGLE_MAPS || "#",
    },
    livestreaming: {
        enabled: process.env.NEXT_PUBLIC_LIVE_STREAMING === 'true',
        time: process.env.NEXT_PUBLIC_LIVE_STREAMING_TIME || "6:00 PM",
        link: process.env.NEXT_PUBLIC_LIVE_STREAMING_LINK || "#",
        detail: process.env.NEXT_PUBLIC_LIVE_STREAMING_DETAIL || "Join us online and celebrate this special day with everyone, wherever you are.",
    },
    prewedding: {
        enabled: process.env.NEXT_PUBLIC_PREWEDDING === 'true',
        link: process.env.NEXT_PUBLIC_PREWEDDING_CODE_LINK_EMBED || "#",
        detail: process.env.NEXT_PUBLIC_PREWEDDING_DETAIL || "A glimpse into our journey, our joy, and the love that brought us here.",
    },
    rsvp: {
        enabled: process.env.NEXT_PUBLIC_RSVP === 'true',
        detail: process.env.NEXT_PUBLIC_RSVP_DETAIL || "Leave your warmest birthday wishes for Asla and let her know you're celebrating with her.",
    },
    thankyou: process.env.NEXT_PUBLIC_THANKYOU || "Thank You",
    thankyouDetail: process.env.NEXT_PUBLIC_THANKYOU_DETAIL || "Thank you for being part of Asla's story — for your love, your laughter, and for making this birthday one she'll never forget.",
};
